<?php $avis = $avis ?? []; $moyenne = $moyenne ?? 0; $noteFiltre = $noteFiltre ?? null; $compteurs = $compteurs ?? array_fill(1, 5, 0); $maxCompteur = $maxCompteur ?? 1; $avisAffiches = $avisAffiches ?? []; $erreur = $erreur ?? null; require __DIR__ . '/../includes/header.php'; ?>
<div class="wrap page-head"><h1>Avis des adhérents</h1><p class="lead">Découvrez les retours de celles et ceux qui s’entraînent chez Apex Fitness.</p></div>
<div class="wrap section">
<?php if (!$avis): ?><div class="vide">Aucun avis publié pour le moment.</div><?php else: ?>
<div class="avis-synthese"><div class="note-moyenne-panel"><h2>Note moyenne</h2><p class="mono" style="font-size:24px;color:#D9942B"><?= str_repeat('★', (int) round($moyenne)) . str_repeat('☆', 5 - (int) round($moyenne)) ?></p><p class="prix" style="font-size:28px;margin:0"><?= number_format($moyenne, 1, ',', ' ') ?> / 5</p><p class="muted"><?= count($avis) ?> avis publié<?= count($avis) > 1 ? 's' : '' ?></p></div>
<div class="filtre-note-panel"><div class="filtre-etoiles"><a class="filtre-etoile total <?= $noteFiltre === null ? 'active' : '' ?>" href="avis.php"><span class="label-total">Total</span><span class="barre-note"><span class="remplissage" style="width:100%"></span></span><span class="count"><?= count($avis) ?></span></a>
<?php for ($note = 5; $note >= 1; $note--): ?><a class="filtre-etoile <?= $noteFiltre === $note ? 'active' : '' ?>" href="avis.php?note=<?= $note ?>"><span class="stars"><?= str_repeat('★', $note) . str_repeat('☆', 5 - $note) ?></span><span class="barre-note"><span class="remplissage" style="width:<?= $compteurs[$note] / $maxCompteur * 100 ?>%"></span></span><span class="count"><?= $compteurs[$note] ?></span></a><?php endfor; ?></div></div></div>
<div class="grille-3"><?php foreach ($avisAffiches as $item): ?><article class="carte"><p class="mono"><?= str_repeat('★', (int) $item['noteavis']) . str_repeat('☆', 5 - (int) $item['noteavis']) ?></p><p><?= nl2br(e($item['commentaire'])) ?></p><?php if (!empty($item['reponse'])): ?><div class="reponse-admin"><strong>Réponse de l’équipe Apex Fitness</strong><p><?= nl2br(e($item['reponse'])) ?></p></div><?php endif; ?><p class="muted"><?= e($item['prenomUsers'] . ' ' . $item['nomUsers']) ?> &middot; <?= dateFr($item['date_interaction']) ?></p></article><?php endforeach; ?></div>
<?php endif; ?>
<?php if ($erreur): ?><p class="flash flash-erreur"><?= e($erreur) ?></p><?php endif; ?>
<?php if (connecte() && a_role('ADHERENT') && !a_role('EMPLOYE')): ?><section class="form" style="max-width:620px;margin-top:26px"><h2>Donner votre avis</h2><form method="post"><?= champ_csrf() ?><div class="form-ligne"><label for="note">Note</label><select id="note" name="note" required><?php for ($n = 5; $n > 0; $n--): ?><option value="<?= $n ?>"><?= $n ?> / 5</option><?php endfor; ?></select></div><div class="form-ligne"><label for="commentaire">Votre commentaire</label><textarea id="commentaire" name="commentaire" minlength="10" maxlength="1000" required></textarea></div><button class="btn btn-vert" type="submit">Publier mon avis</button></form></section><?php elseif (!connecte()): ?><p class="note">Connectez-vous en tant qu’adhérent pour publier un avis.</p><?php endif; ?></div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
